trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Install Terraform
- script: |
    wget https://releases.hashicorp.com/terraform/1.12.2/terraform_1.12.2_linux_amd64.zip
    unzip terraform_1.12.2_linux_amd64.zip
    sudo mv terraform /usr/local/bin/
    terraform version
  displayName: "Install Terraform"

# Azure Login (IMPORTANT FIX)
- task: AzureCLI@2
  displayName: "Azure Login"
  inputs:
    azureSubscription: "azure-sp-conn"
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      set -e
      az account show

# Terraform Init
- script: |
    set -e
    terraform init
  displayName: "Terraform Init"

# Terraform Validate
- script: |
    set -e
    terraform validate
  displayName: "Terraform Validate"

# Terraform Plan
- script: |
    set -e
    terraform plan
  displayName: "Terraform Plan"

# Terraform Apply
- script: |
    set -e
    terraform apply -auto-approve
  displayName: "Terraform Apply"